import { initTheme } from '../../assets/js/utils.js';
import { initDevTrigger } from '../../dev-access/trigger.js';
import { savePrompt } from '../../assets/js/firestore.js';
import { promptDatabase } from './database.js';

const grid=document.getElementById('gallery-grid'), search=document.getElementById('gallery-search'), tabs=document.getElementById('tabs-container'), toast=document.getElementById('toast');
let category='All', sort='newest', subject='all', engine='all', query='', page=1; const perPage=9;
const icon=(name)=>({heart:'♡',share:'↗',copy:'⧉'}[name]||'');
function allItems(){return Object.entries(promptDatabase).flatMap(([key,items])=>items.map((raw,index)=>({id:`${key}-${raw.id||index}`,imageUrl:raw.ai_image||'',refImage:raw.ref_image||'',promptText:raw.prompt||'',category:key,subject:raw.subject||'',dateAdded:raw.createdAt||0})))}
let activeShareId = null;
function filtered(){let list=allItems();if(activeShareId){return list.filter(x=>x.id===activeShareId)}if(category!=='All')list=list.filter(x=>x.category.toLowerCase()===category.toLowerCase());if(subject!=='all')list=list.filter(x=>x.subject.toLowerCase()===subject);if(query)list=list.filter(x=>`${x.promptText} ${x.category} ${x.subject}`.toLowerCase().includes(query.toLowerCase()));list.sort((a,b)=>sort==='newest'?b.dateAdded-a.dateAdded:a.dateAdded-b.dateAdded);return list}
function render(){const list=filtered(), total=Math.ceil(list.length/perPage)||1;page=Math.min(page,total);const shown=list.slice((page-1)*perPage,page*perPage);document.getElementById('results-count').textContent=list.length;grid.innerHTML='';shown.forEach(item=>grid.appendChild(card(item)));renderPagination(total);const filtersEl = document.querySelector('.filters'); let clearBtn = document.getElementById('clear-share-btn'); if(activeShareId){if(!clearBtn){clearBtn=document.createElement('button');clearBtn.id='clear-share-btn';clearBtn.className='tab-btn active';clearBtn.style.background='var(--cyan)';clearBtn.style.color='#000';clearBtn.textContent='← Back to Full Gallery';clearBtn.addEventListener('click',()=>{activeShareId=null;const url=new URL(window.location);url.searchParams.delete('share_id');window.history.replaceState({},'',url);renderTabs();render()});filtersEl.prepend(clearBtn)}}else{if(clearBtn)clearBtn.remove()}}
function card(item){const el=document.createElement('article');el.className='gallery-card';const engineName=engine==='all'?'Flux.1 Schnell':engine==='midjourney'?'Midjourney v6.1':engine==='stable'?'Stable Diffusion 3.5':engine==='dalle'?'DALL·E 3':'Flux.1';const tags=['Cinematic','Photoreal','Editorial'];el.innerHTML=`<div class="card-image-wrapper"><img class="card-image" src="${item.imageUrl}" alt="${item.category} AI prompt result" loading="lazy"><span class="category-tag">${item.category}</span>${item.refImage?'<button class="image-toggle-btn">View Original</button>':''}<div class="image-actions"><button class="like-btn">${icon('heart')} <span>${(1.2+(item.dateAdded%400)/100).toFixed(1)}k</span></button><button class="share-btn">${icon('share')} Share</button></div></div><div class="card-body"><span class="engine-badge">${engineName}</span><h3>Prompt Recipe</h3><p class="recipe">${item.promptText}</p><button class="view-more">View more</button><div class="tags">${tags.map(t=>`<span>#${t}</span>`).join('')}</div><div class="card-bottom"><button class="copy-btn">${icon('copy')} Copy prompt</button><span class="author-meta">${item.subject||'Visual'} · 2025</span></div></div>`;const img=el.querySelector('img'),toggle=el.querySelector('.image-toggle-btn');toggle?.addEventListener('click',()=>{const original=img.src===item.imageUrl;img.src=original?item.refImage:item.imageUrl;toggle.textContent=original?'View AI Generated':'View Original'});el.querySelector('.view-more').addEventListener('click',e=>{el.querySelector('.recipe').classList.toggle('expanded');e.target.textContent=el.querySelector('.recipe').classList.contains('expanded')?'Show less':'View more'});el.querySelector('.copy-btn').addEventListener('click',async e=>{await navigator.clipboard?.writeText(item.promptText);e.target.textContent='Copied';showToast('Prompt copied')});el.querySelector('.like-btn').addEventListener('click',e=>{e.currentTarget.classList.toggle('liked')});el.querySelector('.share-btn').addEventListener('click',async()=>{const url=new URL(window.location);url.searchParams.set('share_id',item.id);const shareUrl=url.toString();try{await navigator.share?.({title:`PromptoEngine - ${item.category} Prompt`,text:item.promptText,url:shareUrl});showToast('Shared successfully')}catch(err){if(err.name!=='AbortError'){await navigator.clipboard?.writeText(shareUrl);showToast('Link copied to clipboard')}}});return el}
function renderPagination(total){const p=document.getElementById('pagination');p.innerHTML='';[['Previous',page-1],...Array.from({length:total},(_,i)=>[i+1,i+1]),['Next',page+1]].forEach(([label,value])=>{const b=document.createElement('button');b.textContent=label;b.disabled=value<1||value>total;b.className=value===page?'active':'';b.addEventListener('click',()=>{page=value;render();scrollTo({top:document.querySelector('.gallery-section').offsetTop-20,behavior:'smooth'})});p.appendChild(b)})}
function renderTabs(){const names=['All',...Object.keys(promptDatabase),'Cyberpunk'];tabs.innerHTML='';names.forEach(name=>{const b=document.createElement('button');b.className=`tab-btn ${name===category?'active':''}`;b.textContent=name;b.addEventListener('click',()=>{category=name;page=1;renderTabs();render()});tabs.appendChild(b)})}
function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function init(){initTheme();initDevTrigger();const urlParams=new URLSearchParams(window.location.search);const sid=urlParams.get('share_id');if(sid){activeShareId=sid;}renderTabs();render();search.addEventListener('input',e=>{query=e.target.value;page=1;activeShareId=null;render()});document.getElementById('search-btn').addEventListener('click',()=>{query=search.value;page=1;activeShareId=null;render()});document.getElementById('sort-select').addEventListener('change',e=>{sort=e.target.value;render()});document.getElementById('subject-select').addEventListener('change',e=>{subject=e.target.value;render()});document.getElementById('engine-select').addEventListener('change',e=>{engine=e.target.value;render()});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();search.focus()}})}
document.addEventListener('DOMContentLoaded',init);
